name: testflow
description: Testing tool
publish_to: none
version: 0.0.1+1

environment:
  sdk: '>=3.6.2 <4.0.0'

dependencies:
  get_it: ^8.0.3
  logger: ^2.5.0
  dafluta: ^5.4.0
  event_bus: ^2.0.1
  shadcn_ui: ^0.18.7

  flutter:
    sdk: flutter

dev_dependencies:
  dalocale: ^2.5.0
  daassets: ^1.5.0
  daunused: ^1.6.1
  dapublock: ^1.1.0
  build_runner: ^2.4.14
  flutter_lints: ^5.0.0
  json_serializable: ^6.9.3

flutter:
  uses-material-design: true